<?php
namespace common\components;

use yii\data\Pagination;

/**
 * 重写分页类
 * extends system Pagination
 */

 class MyPagination extends Pagination{

     public function init()
     {
         parent::init(); // TODO: Change the autogenerated stub
     }



 }

