<?php
namespace common\components\gridop;

use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

class GridopWidget extends Widget
{
    public $items;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $html[] = '<div class="dropdown btn-group">';
        $defaultBtnClass = 'btn btn-default btn-sm';
        if (isset($this->items['title'])) {
            $defaultBtnClass = isset($this->items['title']['class'])?$this->items['title']['class']:$defaultBtnClass;
            $html[] = Html::a(
                $this->items['title']['label'],
                $this->items['title']['url'],
                ArrayHelper::merge(
                    ['class' =>$defaultBtnClass],
                    isset($this->items['title']['options'])?$this->items['title']['options']:[]
                )
            );
        }

        $html[] = '<a data-toggle="dropdown" class="'.$defaultBtnClass.' dropdown-toggle" type="button" href="#"><span class="caret"></span></a>';

        if (isset($this->items['items'])) {
            $html[] = '<ul class="dropdown-menu">';
            foreach ($this->items['items'] as $key => $val) {
                $html[] = '<li>' . Html::a(
                        $val['label'],
                        $val['url'],
                        isset($val['options'])?$val['options']:[]
                    ) . '</li>';
            }
            $html[] = '</ul>';
        }

        $html[] = '</div>';
        return implode("", $html);
    }
}